/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Background.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Background.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 0, -8]} />
        <mesh name="Cactus1" geometry={nodes.Cactus1.geometry} material={materials['Material.001']} rotation={[0, 0, -Math.PI / 2]} scale={0.085} />
        <group name="Plane001">
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.001']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials.Material} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.003']} position={[0, 3.768, -200]} scale={44.62} />
      </group>
    </group>
  )
}

useGLTF.preload('/Background.glb')
