/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Compressed_Background.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Compressed_Background.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.004']} />
        <mesh name="Cactus1" geometry={nodes.Cactus1.geometry} material={materials['Material.003']} position={[-0.252, 0, 0]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.005']} position={[0, 0.014, -321.833]} scale={52.712} />
      </group>
    </group>
  )
}

useGLTF.preload('/Compressed_Background.glb')
