/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Background.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/Background.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action?.reset().setLoop(THREE.LoopRepeat, Infinity).play();
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 0, -8]} />
        <mesh
          name="Cactus1"
          geometry={nodes.Cactus1.geometry}
          material={materials["Material.001"]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.085}
        />
        <group name="Plane001">
          <mesh
            name="Plane003"
            geometry={nodes.Plane003.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Plane003_1"
            geometry={nodes.Plane003_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="Plane003_2"
            geometry={nodes.Plane003_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={materials["Material.003"]}
          position={[0, 3.768, -200]}
          scale={44.62}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Background.glb");

// Camera Animation Component
export function CameraAnimation() {
  const { camera } = useThree();
  const timeRef = useRef(0);
  const startZRef = useRef(null);

  useEffect(() => {
    // Store initial Z position
    if (startZRef.current === null) {
      startZRef.current = camera.position.z;
    }
  }, [camera]);

  useFrame((state, delta) => {
    if (startZRef.current === null) return;

    // Increment time
    timeRef.current += delta;

    // Total duration: 5 seconds
    const duration = 5;
    const progress = (timeRef.current % duration) / duration; // 0 to 1

    const zOffset = progress * 32;
    camera.position.z = startZRef.current + zOffset;
  });

  return null;
}
